### ISSUE TITLE
Notice of 2 invalid options during make

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#1020]
During `make` of latest master, the log contains this:
```
Invalid Option: Unexpected option value "false" for rule "no-descending-specificity"
Invalid Option: Unexpected option value "false" for rule "no-duplicate-selectors"
```

We should make sure that make runs through cleanly without any warnings or errors, even if they don’t break anything. :)

**Comment by georgehrke** [comment]
Since #926 was merged, make works as expected again.

**Comment by jancborchardt** [comment]
I only got these 2 test errors, unrelated to above but still issue during make:

```
 FAIL  js/vendor/jstzdetect/utilities/test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/@jest/core/build/TestScheduler.js:242:24
      at asyncGeneratorStep (node_modules/@jest/core/build/TestScheduler.js:131:24)
      at _next (node_modules/@jest/core/build/TestScheduler.js:151:9)
      at node_modules/@jest/core/build/TestScheduler.js:156:7
      at node_modules/@jest/core/build/TestScheduler.js:148:12
      at onResult (node_modules/@jest/core/build/TestScheduler.js:271:25)

Summary of all failing tests
 FAIL  js/vendor/jstzdetect/utilities/test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/@jest/core/build/TestScheduler.js:242:24
      at asyncGeneratorStep (node_modules/@jest/core/build/TestScheduler.js:131:24)
      at _next (node_modules/@jest/core/build/TestScheduler.js:151:9)
      at node_modules/@jest/core/build/TestScheduler.js:156:7
      at node_modules/@jest/core/build/TestScheduler.js:148:12
      at onResult (node_modules/@jest/core/build/TestScheduler.js:271:25)


Test Suites: 1 failed, 38 passed, 39 total
```

**Comment by georgehrke** [comment]
Ah, `js/vendor` is an old folder from version 1.
Let me just delete the entire `js/` folder on make
