### ISSUE TITLE
make command failed

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#133]
@georgehrke @raghunayyar any idea what’s the issue here?

```
jan@Rechenknecht:~/nextcloud/apps/calendar$ sudo make
make npm
make[1] : on entre dans le répertoire « /home/jan/nextcloud/apps/calendar »
cd js && /usr/bin/npm run build

> calendar@ prebuild /home/jan/nextcloud/apps/calendar/js
> npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the calendar@ prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jan/nextcloud/apps/calendar/js/npm-debug.log
Makefile:92 : la recette pour la cible « npm » a échouée
make[1]: *** [npm] Erreur 1
make[1] : on quitte le répertoire « /home/jan/nextcloud/apps/calendar »
Makefile:87 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 2
```

npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.8
3 info using node@v6.8.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle calendar@~prebuild: calendar@
6 verbose lifecycle calendar@~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle calendar@~prebuild: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/jan/nextcloud/apps/calendar/js/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
8 verbose lifecycle calendar@~prebuild: CWD: /home/jan/nextcloud/apps/calendar/js
9 silly lifecycle calendar@~prebuild: Args: [ '-c',
9 silly lifecycle   'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update' ]
10 silly lifecycle calendar@~prebuild: Returned: code: 1  signal: null
11 info lifecycle calendar@~prebuild: Failed to exec prebuild script
12 verbose stack Error: calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:877:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid calendar@
14 verbose cwd /home/jan/nextcloud/apps/calendar/js
15 error Linux 4.4.0-42-generic
16 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
17 error node v6.8.1
18 error npm  v3.10.8
19 error code ELIFECYCLE
20 error calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
20 error Exit status 1
21 error Failed at the calendar@ prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the calendar package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs calendar
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls calendar
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by tcitworld** [comment]
Why run with sudo ? Bower doesn't allow running as root by default.

**Comment by jancborchardt** [comment]
Cause without it, the error is the same. ;D So I tried with sudo.

**Comment by tcitworld** [comment]
Sure that the error is exactly the same ? I've had issues with bower lately, did you try to update it ? Is it installed globally or locally ?

**Comment by jancborchardt** [comment]
Without sudo it’s like this:

```
jan@Rechenknecht:~/nextcloud/apps/calendar$ make
make npm
make[1] : on entre dans le répertoire « /home/jan/nextcloud/apps/calendar »
cd js && /usr/bin/npm run build

> calendar@ prebuild /home/jan/nextcloud/apps/calendar/js
> npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/home/jan/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.get (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the calendar@ prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jan/nextcloud/apps/calendar/js/npm-debug.log
Makefile:92 : la recette pour la cible « npm » a échouée
make[1]: *** [npm] Erreur 1
make[1] : on quitte le répertoire « /home/jan/nextcloud/apps/calendar »
Makefile:87 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 2
```

npm-debug.log
```
jan@Rechenknecht:~/nextcloud/apps/calendar$ cat js/npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.8
3 info using node@v6.8.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle calendar@~prebuild: calendar@
6 verbose lifecycle calendar@~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle calendar@~prebuild: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/jan/nextcloud/apps/calendar/js/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jan/.rvm/bin:/home/jan/.rvm/bin
8 verbose lifecycle calendar@~prebuild: CWD: /home/jan/nextcloud/apps/calendar/js
9 silly lifecycle calendar@~prebuild: Args: [ '-c',
9 silly lifecycle   'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update' ]
10 silly lifecycle calendar@~prebuild: Returned: code: 1  signal: null
11 info lifecycle calendar@~prebuild: Failed to exec prebuild script
12 verbose stack Error: calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:877:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid calendar@
14 verbose cwd /home/jan/nextcloud/apps/calendar/js
15 error Linux 4.4.0-42-generic
16 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
17 error node v6.8.1
18 error npm  v3.10.8
19 error code ELIFECYCLE
20 error calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
20 error Exit status 1
21 error Failed at the calendar@ prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the calendar package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs calendar
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls calendar
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by tcitworld** [comment]
You should try deleting the `js/node_modules` and running make again.

**Comment by jancborchardt** [comment]
Still similar here:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/home/jan/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.get (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the calendar@ prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jan/nextcloud/apps/calendar/js/npm-debug.log
Makefile:92 : la recette pour la cible « npm » a échouée
make[1]: *** [npm] Erreur 1
make[1] : on quitte le répertoire « /home/jan/nextcloud/apps/calendar »
Makefile:87 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 2
```

**Comment by tcitworld** [comment]
And if you install bower globally ? `sudo npm -g i bower`

**Comment by georgehrke** [comment]
And please fix the permissions:
```
Error: EACCES: permission denied, open '/home/jan/.config/configstore/bower-github.json'
```

**Comment by tcitworld** [comment]
```
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
```

**Comment by jancborchardt** [comment]
Which user/group? jan:jan?

**Comment by jancborchardt** [comment]
(Cause I run these commands as my user)

**Comment by tcitworld** [comment]
Yup.

**Comment by jancborchardt** [comment]
Was already set though:
```
jan@Rechenknecht:~$ ls -la | grep .npm
drwxr-xr-x 1400 jan      jan      65536 Okt 11 13:47 .npm
jan@Rechenknecht:~$ ls -la | grep .config
drwx------   84 jan      jan       4096 Okt  4 19:58 .config
```

**Comment by jancborchardt** [comment]
Aaaah ok, that specific file is owned by root …

**Comment by tcitworld** [comment]
What about `.config/configstore/bower-github.json` ?

**Comment by jancborchardt** [comment]
Now it’s this:
```
jan@Rechenknecht:~/nextcloud/apps/calendar$ make
make npm
make[1] : on entre dans le répertoire « /home/jan/nextcloud/apps/calendar »
cd js && /usr/bin/npm run build

> calendar@ prebuild /home/jan/nextcloud/apps/calendar/js
> npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower fullcalendar#3.0.1    not-cached https://github.com/fullcalendar/fullcalendar.git#3.0.1
bower fullcalendar#3.0.1       resolve https://github.com/fullcalendar/fullcalendar.git#3.0.1
bower angular-bootstrap#2.2.0       not-cached https://github.com/angular-ui/bootstrap-bower.git#2.2.0
bower angular-bootstrap#2.2.0          resolve https://github.com/angular-ui/bootstrap-bower.git#2.2.0
bower angular-bootstrap#2.2.0         checkout 2.2.0
bower fullcalendar#3.0.1              checkout v3.0.1
bower angular-bootstrap#2.2.0         resolved https://github.com/angular-ui/bootstrap-bower.git#2.2.0
bower fullcalendar#3.0.1              resolved https://github.com/fullcalendar/fullcalendar.git#3.0.1
bower fullcalendar#3.0.1               skipped jquery
bower fullcalendar#3.0.1               skipped moment
bower angular-bootstrap#2.2.0          install angular-bootstrap#2.2.0
bower fullcalendar#3.0.1               install fullcalendar#3.0.1
/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/q/q.js:155
                throw e;
                ^

TypeError: Cannot read property '_release' of undefined
    at StandardRenderer._tree2archy (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/renderers/StandardRenderer.js:438:47)
    at Array.map (native)
    at StandardRenderer._tree2archy (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/renderers/StandardRenderer.js:490:49)
    at StandardRenderer.<anonymous> (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/renderers/StandardRenderer.js:161:24)
    at /home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/mout/object/forOwn.js:12:27
    at exec (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/mout/object/forIn.js:71:19)
    at forIn (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/mout/object/forIn.js:38:17)
    at Object.forOwn (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/node_modules/mout/object/forOwn.js:10:9)
    at StandardRenderer._install (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/renderers/StandardRenderer.js:149:17)
    at StandardRenderer.end (/home/jan/nextcloud/apps/calendar/js/node_modules/bower/lib/renderers/StandardRenderer.js:50:21)

npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the calendar@ prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jan/nextcloud/apps/calendar/js/npm-debug.log
Makefile:92 : la recette pour la cible « npm » a échouée
make[1]: *** [npm] Erreur 1
make[1] : on quitte le répertoire « /home/jan/nextcloud/apps/calendar »
Makefile:87 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 2
jan@Rechenknecht:~/nextcloud/apps/calendar$ cat js/npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.8
3 info using node@v6.8.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle calendar@~prebuild: calendar@
6 verbose lifecycle calendar@~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle calendar@~prebuild: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/jan/nextcloud/apps/calendar/js/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jan/.rvm/bin:/home/jan/.rvm/bin
8 verbose lifecycle calendar@~prebuild: CWD: /home/jan/nextcloud/apps/calendar/js
9 silly lifecycle calendar@~prebuild: Args: [ '-c',
9 silly lifecycle   'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update' ]
10 silly lifecycle calendar@~prebuild: Returned: code: 1  signal: null
11 info lifecycle calendar@~prebuild: Failed to exec prebuild script
12 verbose stack Error: calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:877:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid calendar@
14 verbose cwd /home/jan/nextcloud/apps/calendar/js
15 error Linux 4.4.0-42-generic
16 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
17 error node v6.8.1
18 error npm  v3.10.8
19 error code ELIFECYCLE
20 error calendar@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
20 error Exit status 1
21 error Failed at the calendar@ prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the calendar package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs calendar
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls calendar
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by tcitworld** [comment]
I tried upgrading to your current nodejs version, no changes. Maybe clear the `js/vendor` directory too.

**Comment by jancborchardt** [comment]
@tcitworld awesome, that did it! :) Thanks a lot. This is probably only an isolated problem of mine, or could it be solved in the make script?

**Comment by georgehrke** [comment]
> This is probably only an isolated problem of mine

I think so. Running it with sudo first probably created too many files with wrong (root) permissions.
Solving this in the Makefile is difficult, when we don't want people to run the makefile without sudo.

We should add to the Readme, that make is supposed to run neither with root nor with sudo.
Will take care.

**Comment by tcitworld** [comment]
Nope, I had the issue too (`Cannot read property '_release' of undefined`) a couple of weeks ago. No idea from where it came from (nodejs, bower, 3rd party library ?).
Maybe we can add a step to clean the vendor directories in the make command ?

**Comment by georgehrke** [comment]
there is `make cleandist`

**Comment by georgehrke** [comment]
added a note in https://github.com/nextcloud/calendar/pull/135

**Comment by jancborchardt** [comment]
@georgehrke thanks a lot! :)
