### ISSUE TITLE
Error connecting to client

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/calendar#1909]
When trying to connect to the OpenSync 1.5.0.3-ose and
DAVx5 2.6.3.1-ose client receives a connection error.
Customer logs:

OpenSync 1.5.0.3-ose
```
--- BEGIN DEBUG INFO ---

LOGS:
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Finding initial carddav service configuration
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Checking user-given URL: http://cloud.xxx.pl/
2020-01-25 14:14:43 1 [HttpClient$1] --> PROPFIND http://cloud.xxx.pl/ http/1.1
2020-01-25 14:14:43 1 [HttpClient$1] Content-Type: application/xml; charset=utf-8
2020-01-25 14:14:43 1 [HttpClient$1] Content-Length: 290
2020-01-25 14:14:43 1 [HttpClient$1] Depth: 0
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><displayname /><CARD:addressbook-description /><CARD:addressbook-home-set /><current-user-principal /></prop></propfind>
2020-01-25 14:14:43 1 [HttpClient$1] --> END PROPFIND (290-byte body)
2020-01-25 14:14:43 1 [HttpClient$1] <-- 405 Method Not Allowed http://cloud.xxx.pl/ (163ms)
2020-01-25 14:14:43 1 [HttpClient$1] date: Sat, 25 Jan 2020 13:14:43 GMT
2020-01-25 14:14:43 1 [HttpClient$1] server: Apache
2020-01-25 14:14:43 1 [HttpClient$1] allow: OPTIONS,HEAD,GET,POST,TRACE
2020-01-25 14:14:43 1 [HttpClient$1] content-length: 359
2020-01-25 14:14:43 1 [HttpClient$1] content-type: text/html; charset=iso-8859-1
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method GET is not allowed for the URL /index.html.</p>
<p>Additionally, a 405 Method Not Allowed
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 14:14:43 1 [HttpClient$1] <-- END HTTP (359-byte body)
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] PROPFIND/OPTIONS on user-given URL failed
EXCEPTION at.bitfire.dav4android.exception.HttpException: 405 Method Not Allowed
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:325)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:298)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:283)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.checkUserGivenURL(DavResourceFinder.java:179)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:119)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:90)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:142)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:125)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

2020-01-25 14:14:43 1 [HttpClient$1] --> PROPFIND http://cloud.xxx.pl/.well-known/carddav http/1.1
2020-01-25 14:14:43 1 [HttpClient$1] Content-Type: application/xml; charset=utf-8
2020-01-25 14:14:43 1 [HttpClient$1] Content-Length: 198
2020-01-25 14:14:43 1 [HttpClient$1] Depth: 0
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><current-user-principal /></prop></propfind>
2020-01-25 14:14:43 1 [HttpClient$1] --> END PROPFIND (198-byte body)
2020-01-25 14:14:43 1 [HttpClient$1] <-- 500 Internal Server Error http://cloud.xxx.pl/.well-known/carddav (50ms)
2020-01-25 14:14:43 1 [HttpClient$1] date: Sat, 25 Jan 2020 13:14:43 GMT
2020-01-25 14:14:43 1 [HttpClient$1] server: Apache
2020-01-25 14:14:43 1 [HttpClient$1] content-length: 668
2020-01-25 14:14:43 1 [HttpClient$1] content-type: text/html; charset=iso-8859-1
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@cloud.xxx.pl to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 14:14:43 1 [HttpClient$1] <-- END HTTP (668-byte body)
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Well-known URL detection failed
EXCEPTION at.bitfire.dav4android.exception.HttpException: 500 Internal Server Error
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:325)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:298)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:283)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:352)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:123)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:90)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:142)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:125)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Finding initial caldav service configuration
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Checking user-given URL: http://cloud.xxx.pl/
2020-01-25 14:14:43 1 [HttpClient$1] --> PROPFIND http://cloud.xxx.pl/ http/1.1
2020-01-25 14:14:43 1 [HttpClient$1] Content-Type: application/xml; charset=utf-8
2020-01-25 14:14:43 1 [HttpClient$1] Content-Length: 435
2020-01-25 14:14:43 1 [HttpClient$1] Depth: 0
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><displayname /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:calendar-description /><CAL:calendar-timezone /><current-user-privilege-set /><CAL:supported-calendar-component-set /><CAL:calendar-home-set /><current-user-principal /></prop></propfind>
2020-01-25 14:14:43 1 [HttpClient$1] --> END PROPFIND (435-byte body)
2020-01-25 14:14:43 1 [HttpClient$1] <-- 405 Method Not Allowed http://cloud.xxx.pl/ (45ms)
2020-01-25 14:14:43 1 [HttpClient$1] date: Sat, 25 Jan 2020 13:14:43 GMT
2020-01-25 14:14:43 1 [HttpClient$1] server: Apache
2020-01-25 14:14:43 1 [HttpClient$1] allow: OPTIONS,HEAD,GET,POST,TRACE
2020-01-25 14:14:43 1 [HttpClient$1] content-length: 359
2020-01-25 14:14:43 1 [HttpClient$1] content-type: text/html; charset=iso-8859-1
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method GET is not allowed for the URL /index.html.</p>
<p>Additionally, a 405 Method Not Allowed
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 14:14:43 1 [HttpClient$1] <-- END HTTP (359-byte body)
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] PROPFIND/OPTIONS on user-given URL failed
EXCEPTION at.bitfire.dav4android.exception.HttpException: 405 Method Not Allowed
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:325)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:298)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:283)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.checkUserGivenURL(DavResourceFinder.java:187)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:119)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:91)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:142)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:125)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

2020-01-25 14:14:43 1 [HttpClient$1] --> PROPFIND http://cloud.xxx.pl/.well-known/caldav http/1.1
2020-01-25 14:14:43 1 [HttpClient$1] Content-Type: application/xml; charset=utf-8
2020-01-25 14:14:43 1 [HttpClient$1] Content-Length: 198
2020-01-25 14:14:43 1 [HttpClient$1] Depth: 0
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><current-user-principal /></prop></propfind>
2020-01-25 14:14:43 1 [HttpClient$1] --> END PROPFIND (198-byte body)
2020-01-25 14:14:43 1 [HttpClient$1] <-- 500 Internal Server Error http://cloud.xxx.pl/.well-known/caldav (54ms)
2020-01-25 14:14:43 1 [HttpClient$1] date: Sat, 25 Jan 2020 13:14:43 GMT
2020-01-25 14:14:43 1 [HttpClient$1] server: Apache
2020-01-25 14:14:43 1 [HttpClient$1] content-length: 668
2020-01-25 14:14:43 1 [HttpClient$1] content-type: text/html; charset=iso-8859-1
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@cloud.xxx.pl to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 14:14:43 1 [HttpClient$1] <-- END HTTP (668-byte body)
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Well-known URL detection failed
EXCEPTION at.bitfire.dav4android.exception.HttpException: 500 Internal Server Error
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:325)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:298)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:283)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:352)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:123)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:91)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:142)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:125)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)



SOFTWARE INFORMATION
OpenSync version: 1.5.0.3-ose (145) Tue Apr 18 09:03:24 GMT+02:00 2017
Installed from: com.android.vending
JB Workaround installed: no
```
DAVx5 2.6.3.1-ose
```
--- BEGIN DEBUG INFO ---

LOGS:
2020-01-25 15:28:25 2 [ui.setup.DavResourceFinder] Finding initial carddav service configuration
2020-01-25 15:28:25 2 [ui.setup.DavResourceFinder] Checking user-given URL: http://cloud.xxx.pl/
2020-01-25 15:28:25 2 [HttpClient] --> PROPFIND http://cloud.xxx.pl/
2020-01-25 15:28:26 2 [HttpClient] Content-Type: application/xml; charset=utf-8
2020-01-25 15:28:26 2 [HttpClient] Content-Length: 290
2020-01-25 15:28:26 2 [HttpClient] Depth: 0
2020-01-25 15:28:26 2 [HttpClient] 
2020-01-25 15:28:26 2 [HttpClient] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><displayname /><CARD:addressbook-description /><CARD:addressbook-home-set /><current-user-principal /></prop></propfind>
2020-01-25 15:28:26 2 [HttpClient] --> END PROPFIND (290-byte body)
2020-01-25 15:28:27 2 [HttpClient] <-- 405 Method Not Allowed http://cloud.xxx.pl/ (1366ms)
2020-01-25 15:28:27 2 [HttpClient] date: Sat, 25 Jan 2020 14:28:27 GMT
2020-01-25 15:28:27 2 [HttpClient] server: Apache
2020-01-25 15:28:27 2 [HttpClient] allow: OPTIONS,HEAD,GET,POST,TRACE
2020-01-25 15:28:27 2 [HttpClient] content-length: 359
2020-01-25 15:28:27 2 [HttpClient] content-type: text/html; charset=iso-8859-1
2020-01-25 15:28:27 2 [HttpClient] 
2020-01-25 15:28:27 2 [HttpClient] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method GET is not allowed for the URL /index.html.</p>
<p>Additionally, a 405 Method Not Allowed
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 15:28:27 2 [HttpClient] <-- END HTTP (359-byte body)
2020-01-25 15:28:27 2 [ui.setup.DavResourceFinder] PROPFIND/OPTIONS on user-given URL failed
EXCEPTION at.bitfire.dav4jvm.exception.HttpException: HTTP 405 Method Not Allowed
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:364)
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:338)
	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:432)
	at at.bitfire.dav4jvm.DavResource.propfind(DavResource.kt:325)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.checkUserGivenURL(DavResourceFinder.kt:180)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:115)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:73)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:83)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:62)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

2020-01-25 15:28:27 2 [HttpClient] --> PROPFIND http://cloud.xxx.pl/.well-known/carddav
2020-01-25 15:28:27 2 [HttpClient] Content-Type: application/xml; charset=utf-8
2020-01-25 15:28:27 2 [HttpClient] Content-Length: 198
2020-01-25 15:28:27 2 [HttpClient] Depth: 0
2020-01-25 15:28:27 2 [HttpClient] 
2020-01-25 15:28:27 2 [HttpClient] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><current-user-principal /></prop></propfind>
2020-01-25 15:28:27 2 [HttpClient] --> END PROPFIND (198-byte body)
2020-01-25 15:28:27 2 [HttpClient] <-- 500 Internal Server Error http://cloud.xxx.pl/.well-known/carddav (135ms)
2020-01-25 15:28:27 2 [HttpClient] date: Sat, 25 Jan 2020 14:28:27 GMT
2020-01-25 15:28:27 2 [HttpClient] server: Apache
2020-01-25 15:28:27 2 [HttpClient] content-length: 668
2020-01-25 15:28:27 2 [HttpClient] content-type: text/html; charset=iso-8859-1
2020-01-25 15:28:27 2 [HttpClient] 
2020-01-25 15:28:27 2 [HttpClient] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@cloud.xxx.pl to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 15:28:27 2 [HttpClient] <-- END HTTP (668-byte body)
2020-01-25 15:28:27 2 [ui.setup.DavResourceFinder] Well-known URL detection failed
EXCEPTION at.bitfire.dav4jvm.exception.HttpException: HTTP 500 Internal Server Error
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:364)
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:338)
	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:432)
	at at.bitfire.dav4jvm.DavResource.propfind(DavResource.kt:325)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.kt:385)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:119)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:73)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:83)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:62)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

2020-01-25 15:28:27 2 [ui.setup.DavResourceFinder] Finding initial caldav service configuration
2020-01-25 15:28:27 2 [ui.setup.DavResourceFinder] Checking user-given URL: http://cloud.xxx.pl/
2020-01-25 15:28:27 2 [HttpClient] --> PROPFIND http://cloud.xxx.pl/
2020-01-25 15:28:27 2 [HttpClient] Content-Type: application/xml; charset=utf-8
2020-01-25 15:28:27 2 [HttpClient] Content-Length: 435
2020-01-25 15:28:27 2 [HttpClient] Depth: 0
2020-01-25 15:28:27 2 [HttpClient] 
2020-01-25 15:28:27 2 [HttpClient] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><displayname /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:calendar-description /><CAL:calendar-timezone /><current-user-privilege-set /><CAL:supported-calendar-component-set /><CAL:calendar-home-set /><current-user-principal /></prop></propfind>
2020-01-25 15:28:27 2 [HttpClient] --> END PROPFIND (435-byte body)
2020-01-25 15:28:27 2 [HttpClient] <-- 405 Method Not Allowed http://cloud.xxx.pl/ (180ms)
2020-01-25 15:28:27 2 [HttpClient] date: Sat, 25 Jan 2020 14:28:27 GMT
2020-01-25 15:28:27 2 [HttpClient] server: Apache
2020-01-25 15:28:27 2 [HttpClient] allow: OPTIONS,HEAD,GET,POST,TRACE
2020-01-25 15:28:27 2 [HttpClient] content-length: 359
2020-01-25 15:28:27 2 [HttpClient] content-type: text/html; charset=iso-8859-1
2020-01-25 15:28:27 2 [HttpClient] 
2020-01-25 15:28:27 2 [HttpClient] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method GET is not allowed for the URL /index.html.</p>
<p>Additionally, a 405 Method Not Allowed
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 15:28:27 2 [HttpClient] <-- END HTTP (359-byte body)
2020-01-25 15:28:27 2 [ui.setup.DavResourceFinder] PROPFIND/OPTIONS on user-given URL failed
EXCEPTION at.bitfire.dav4jvm.exception.HttpException: HTTP 405 Method Not Allowed
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:364)
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:338)
	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:432)
	at at.bitfire.dav4jvm.DavResource.propfind(DavResource.kt:325)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.checkUserGivenURL(DavResourceFinder.kt:189)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:115)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:80)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:83)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:62)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

2020-01-25 15:28:27 2 [HttpClient] --> PROPFIND http://cloud.xxx.pl/.well-known/caldav
2020-01-25 15:28:27 2 [HttpClient] Content-Type: application/xml; charset=utf-8
2020-01-25 15:28:27 2 [HttpClient] Content-Length: 198
2020-01-25 15:28:27 2 [HttpClient] Depth: 0
2020-01-25 15:28:27 2 [HttpClient] 
2020-01-25 15:28:27 2 [HttpClient] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><current-user-principal /></prop></propfind>
2020-01-25 15:28:27 2 [HttpClient] --> END PROPFIND (198-byte body)
2020-01-25 15:28:28 2 [HttpClient] <-- 500 Internal Server Error http://cloud.xxx.pl/.well-known/caldav (481ms)
2020-01-25 15:28:28 2 [HttpClient] date: Sat, 25 Jan 2020 14:28:28 GMT
2020-01-25 15:28:28 2 [HttpClient] server: Apache
2020-01-25 15:28:28 2 [HttpClient] content-length: 668
2020-01-25 15:28:28 2 [HttpClient] content-type: text/html; charset=iso-8859-1
2020-01-25 15:28:28 2 [HttpClient] 
2020-01-25 15:28:28 2 [HttpClient] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@cloud.xxx.pl to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 15:28:28 2 [HttpClient] <-- END HTTP (668-byte body)
2020-01-25 15:28:28 2 [ui.setup.DavResourceFinder] Well-known URL detection failed
EXCEPTION at.bitfire.dav4jvm.exception.HttpException: HTTP 500 Internal Server Error
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:364)
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:338)
	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:432)
	at at.bitfire.dav4jvm.DavResource.propfind(DavResource.kt:325)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.kt:385)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:119)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:80)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:83)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:62)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)



SOFTWARE INFORMATION
* at.bitfire.davdroid 2.6.3.1-ose (329)
* com.android.providers.contacts 4.70.54 (470005400)
* com.android.providers.calendar 4.4.10 (404010000)
* com.android.contacts 4.70.54 (470005400)
* com.android.calendar 4.70.18 (47001800)

CONNECTIVITY (at the moment)
- [ Transports: WIFI Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps]

CONFIGURATION
Power saving disabled: no
Notifications (not blocked):
Permissions:
  READ_CONTACTS: denied
  WRITE_CONTACTS: denied
  READ_CALENDAR: denied
  WRITE_CALENDAR: denied
  READ_TASKS: denied
  WRITE_TASKS: denied
  ACCESS_COARSE_LOCATION: denied
System-wide synchronization: manually
```
### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.1

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
OpenSync 1.5.0.3-ose
DAVx5 2.6.3.1-ose

**Operating system:** (e.g. Arch Linux)
Android 6

### Server configuration

**Operating system**: (e.g. Debian 8)
Linux

**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4.39

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
Mysql

**PHP version:** (e.g. 7.0.3)
7.2.14

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18.0.0

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by Valdnet** [comment]
@georgehrke Thanks for the tips. I managed :wink:.
