### ISSUE TITLE
Unable to open calendar app in latest v3.0.0 nor run its cron job

### ISSUE THREAD

**Issue by binarykitchen** [nextcloud/calendar#3753]
Just upgraded to your latest version 3.0.0 and seeing this error:

```
ArgumentCountError: Too few arguments to function OCA\Calendar\BackgroundJob\CleanUpOutdatedBookingsJob::__construct(), 0 passed in /usr/local/lib/owncloud/lib/private/BackgroundJob/JobList.php on line 271 and exactly 3 expected in /usr/local/lib/owncloud/apps/calendar/lib/BackgroundJob/CleanUpOutdatedBookingsJob.php:42
Stack trace:
#0 /usr/local/lib/owncloud/lib/private/BackgroundJob/JobList.php(271): OCA\Calendar\BackgroundJob\CleanUpOutdatedBookingsJob->__construct()
#1 /usr/local/lib/owncloud/lib/private/BackgroundJob/JobList.php(215): OC\BackgroundJob\JobList->buildJob(Array)
#2 /usr/local/lib/owncloud/cron.php(121): OC\BackgroundJob\JobList->getNext()
#3 {main}
```

And a similar related one:

```
{"reqId":"K0WOYtgDjdJQLID6zM9P","level":3,"time":"2021-11-30T09:28:04+13:00","remoteAddr":"121.74.106.133","user":"michael.heuberger@infernaldarkness.com","app":"index","method":"GET","url":"/cloud/index.php/apps/calendar/","message":{"Exception":"ParseError","Message":"syntax error, unexpected ')'","Code":0,"Trace":[{"file":"/usr/local/lib/owncloud/lib/composer/composer/ClassLoader.php","line":322,"function":"Composer\\Autoload\\includeFile","args":["/usr/local/lib/owncloud/apps/calendar/lib//Controller/ViewController.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"function":"spl_autoload_call","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":107,"function":"__construct","class":"ReflectionClass","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/usr/local/lib/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":455,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/usr/local/lib/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":427,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/usr/local/lib/owncloud/lib/private/AppFramework/App.php","line":139,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/usr/local/lib/owncloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Calendar\\Controller\\ViewController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"calendar.view.index"}]},{"file":"/usr/local/lib/owncloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/calendar/"]},{"file":"/usr/local/lib/owncloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/lib/owncloud/apps/calendar/lib/Controller/ViewController.php","Line":118,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36","version":"20.0.14.2","id":"61a5393a1cbb9"}
```

Using Nextcloud version 20.0.14 here.

Hope you guys know what it is. Cannot use my busy calendar now.

**Comment by ChristophWurst** [comment]
You can use your calendar without this.

**Comment by binarykitchen** [comment]
I hear you it is just a cron job. But I also cannot open the calendar app inside Nextcloud as well @ChristophWurst 
<img width="785" alt="Screen Shot 2021-11-30 at 09 38 09" src="https://user-images.githubusercontent.com/177641/143939548-012d9cff-053c-4d3e-a243-f4bbfd444e16.png">

And the latest error log entry indicates a syntax error:

```
[index] Error: ParseError: syntax error, unexpected ')' at <<closure>>

 0. /usr/local/lib/owncloud/lib/composer/composer/ClassLoader.php line 322
    Composer\Autoload\includeFile("/usr/local/lib/ ... p")
 1. <<closure>>
    Composer\Autoload\ClassLoader->loadClass("OCA\\Calendar\\ ... r")
 2. <<closure>>
    spl_autoload_call("OCA\\Calendar\\ ... r")
 3. /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 107
    ReflectionClass->__construct("OCA\\Calendar\\ ... r")
 4. /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 126
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Calendar\\ ... r")
 5. /usr/local/lib/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 455
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Calendar\\ ... r")
 6. /usr/local/lib/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 427
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Calendar\\ ... r")
 7. /usr/local/lib/owncloud/lib/private/AppFramework/App.php line 139
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Calendar\\ ... r")
 8. /usr/local/lib/owncloud/lib/private/Route/Router.php line 309
    OC\AppFramework\App::main("OCA\\Calendar\\ ... r", "index", OC\AppFramework\ ... {}, {_route: "calendar.view.index"})
 9. /usr/local/lib/owncloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/calendar/")
10. /usr/local/lib/owncloud/index.php line 37
    OC::handleRequest()

GET /cloud/index.php/apps/calendar/
from 121.74.106.133 by michael.heuberger@infernaldarkness.com at 2021-11-30T09:38:04+13:00
```

**Comment by ChristophWurst** [comment]
Could you open a full bug report please with *all* details from the template? Thanks.

**Comment by ChristophWurst** [comment]
I suspect this is a trailing comma somewhere. This throw an error because you use php7.2.

**Comment by binarykitchen** [comment]
@ChristophWurst Oh, what's the minimum required PHP version?

**Comment by binarykitchen** [comment]
> Could you open a full bug report please with all details from the template? Thanks.

https://github.com/nextcloud/calendar/issues/3754

**Comment by ChristophWurst** [comment]
Unfortunately there is none specified for the app. Anything older than 7.2 is EOL https://www.php.net/supported-versions.php

**Comment by binarykitchen** [comment]
@ChristophWurst Hmm, what version do you recommend then?

**Comment by ChristophWurst** [comment]
So you use 7.2.

We should have dropped 7.2 explicitly with the v3 release. My bad. Will see what we can do about this tomorrow.

> @ChristophWurst Hmm, what version do you recommend then?

7.4 or 8.0. Your distro should offer it.

**Comment by binarykitchen** [comment]
Unfortunately cannot update PHP right now as that would break some other components on my server, e.g. mail-in-a-box.

**Comment by leinec** [comment]
I posted a quickfix for this bug here: [#3754](https://github.com/nextcloud/calendar/issues/3754)

**Comment by binarykitchen** [comment]
Yep, that worked. Thanks.

**Comment by leinec** [comment]
Thanks for reacting so fast 🤗
