### ISSUE TITLE
Embedded link has no events

### ISSUE THREAD

**Issue by odlg** [nextcloud/calendar#4049]
### Steps to reproduce

1. Make a calendar and add events
2. Share a link and "Copy embedding code"
3. View the embedded link - there are no events shown.

A javascript error is visible in the console:
```
vue.runtime.esm.js:1897 Error: Could not find initial state hide_event_export of calendar
    at e.loadState (index.js:24:11)
    at Calendar.vue:221:1
    at u (dist.js:1:80785)
    at Generator._invoke (dist.js:1:80573)
    at Generator.next (dist.js:1:81214)
    at XF (AppointmentConfigList.vue:127:1)
    at o (AppointmentConfigList.vue:127:1)
    at AppointmentConfigList.vue:127:1
    at new Promise (<anonymous>)
    at AppointmentConfigList.vue:127:1

```

### Expected behavior

Calendar events are shown

### Actual behaviour

Calendar is shown, but empty without events.

### Calendar app version

3.2.0

### Browser

Firefox 97, Chrome 99, Edge 99

### Client operating system

OpenSUSE Linux

### Server operating system

Debian

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

22.2.5

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - accessibility: 1.8.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.0
  - circles: 22.2.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.20.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.5
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - activity: 2.13.3
  - admin_audit
  - contacts: 4.0.8
  - dashboard: 7.0.0
  - encryption
  - files_external
  - mail: 1.11.7
  - notes: 4.3.1
  - photos: 1.2.0
  - richdocumentscode: 21.11.103
  - spreed: 12.2.3
  - user_ldap
```

### Nextcloud configuration

```Text
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.8:8090"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.5.1",
        "overwrite.cli.url": "http:\/\/10.0.0.8:8090",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "cloud.xxxxx.xx",
        "overwriteprotocol": "https",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "default_phone_region": "DK"
    }
}
```

### Browser log

```Text
index.js:46 No OC found
Fr @ index.js:46
value @ gettext.js:45
(anonymous) @ l10n.js:3
(anonymous) @ main.js?v=41b0a30a-23:160
n @ bootstrap:19
(anonymous) @ main.js?v=41b0a30a-23:27
n @ bootstrap:19
(anonymous) @ main.js:1
(anonymous) @ main.js?v=41b0a30a-23:918
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js?v=41b0a30a-23:1
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
get @ globals.js:93
(anonymous) @ jquery.js:10336
(anonymous) @ jquery.js:28
0 @ jquery.js:14
n @ bootstrap:19
707 @ files_client.js?v=41b0a30a-23:64
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=41b0a30a-23:1
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
get @ globals.js:93
(anonymous) @ jquery.js:10339
(anonymous) @ jquery.js:28
0 @ jquery.js:14
n @ bootstrap:19
707 @ files_client.js?v=41b0a30a-23:64
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=41b0a30a-23:1
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
get @ globals.js:93
(anonymous) @ script.js?v=41b0a30a-23:492
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
get @ globals.js:93
(anonymous) @ files.js?v=41b0a30a-23:122
ProxyBus.js:72 Proxying an event bus of version 1.3.0 with 2.1.1
e.ProxyBus @ ProxyBus.js:72
27594 @ index.js:22
s @ bootstrap:19
16 @ AppNavigation.js:24
n @ AppNavigation.js:1
216 @ AppNavigation.js:66
n @ AppNavigation.js:1
(anonymous) @ AppNavigation.js:1
58908 @ AppNavigation.js:1
s @ bootstrap:19
(anonymous) @ vue-router.esm.js:3152
(anonymous) @ main.js:83
(anonymous) @ main.js:83
vue.runtime.esm.js:1897 Error: Could not find initial state hide_event_export of calendar
    at e.loadState (index.js:24:11)
    at Calendar.vue:221:1
    at u (dist.js:1:80785)
    at Generator._invoke (dist.js:1:80573)
    at Generator.next (dist.js:1:81214)
    at XF (AppointmentConfigList.vue:127:1)
    at o (AppointmentConfigList.vue:127:1)
    at AppointmentConfigList.vue:127:1
    at new Promise (<anonymous>)
    at AppointmentConfigList.vue:127:1
qt @ vue.runtime.esm.js:1897
Wt @ vue.runtime.esm.js:1888
$t @ vue.runtime.esm.js:1848
(anonymous) @ vue.runtime.esm.js:1865
Promise.catch (async)
Vt @ vue.runtime.esm.js:1865
ln @ vue.runtime.esm.js:4235
t @ vue.runtime.esm.js:4058
Bn.$mount @ vue.runtime.esm.js:8459
init @ vue.runtime.esm.js:3137
n @ vue.runtime.esm.js:3322
(anonymous) @ vue.runtime.esm.js:6022
d @ vue.runtime.esm.js:5969
gi.nodeOps @ vue.runtime.esm.js:6521
t._update @ vue.runtime.esm.js:3960
r @ vue.runtime.esm.js:4081
bn.get @ vue.runtime.esm.js:4495
bn @ vue.runtime.esm.js:4484
t @ vue.runtime.esm.js:4088
Bn.$mount @ vue.runtime.esm.js:8459
init @ vue.runtime.esm.js:3137
(anonymous) @ vue.runtime.esm.js:6022
d @ vue.runtime.esm.js:5969
gi.nodeOps @ vue.runtime.esm.js:6560
t._update @ vue.runtime.esm.js:3960
r @ vue.runtime.esm.js:4081
bn.get @ vue.runtime.esm.js:4495
bn @ vue.runtime.esm.js:4484
t @ vue.runtime.esm.js:4088
Bn.$mount @ vue.runtime.esm.js:8459
t._init @ vue.runtime.esm.js:5032
Bn @ vue.runtime.esm.js:5099
(anonymous) @ main.js:79
(anonymous) @ main.js:83
(anonymous) @ main.js:83
session-heartbeat.js:101 session heartbeat polling started
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
get @ globals.js:93
(anonymous) @ backgroundjobs.js?v=41b0a30a-23:24
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
get @ globals.js:93
(anonymous) @ backgroundjobs.js?v=41b0a30a-23:26
ConsoleLogger.js:33 [INFO] calendar: Updated moment locale: en {app: 'calendar'}
```

**Comment by tcitworld** [comment]
Duplicate from #4033
