### ISSUE TITLE
User without mail address cannot view or edit certain events

### ISSUE THREAD

**Issue by krumelmonster** [nextcloud/calendar#4203]
### Steps to reproduce

1. Set up nextcloud but don't set the inital users mail adress
2. Create a Calendar and sync in some events using webdav using the account without mail adress
3. Click this event in the calendar overview
4. Errors print in js console (see below) and the event popup won't load, loading spinner show indefinitely
![image](https://user-images.githubusercontent.com/13542760/167397895-f37d3d04-3bb4-45a4-bcea-82e2f60f6839.png)

### Expected behavior

I would expect this popup to show as it does with manually created events
![image](https://user-images.githubusercontent.com/13542760/167398212-5c166b12-9c96-4b6b-a130-63663ca0537a.png)

### Actual behaviour

I have to set my mail address in nextclouds user preferences before I use the calendar app

### Calendar app version

3.3.0

### CalDAV-clients used

vdirsyncer

### Browser

chromium 101.0.4951.54

### Database engine version

MariaDB

### Nextcloud version

Nextcloud Hub II (23.0.4)

### List of activated apps

```Text
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.0
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.12.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.4
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
```

### Web server error log

```Text
No related errors appear in apache logs
```

### Log file

```Text
No related errors appear in nextcloud.log
```

### Browser log

```Text
One of those for each attempt to open such an event

vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'startsWith')
    at lx (attendee.js:30:10)
    at o.userAsAttendee (EditorMixin.js:234:22)
    at bn.get (vue.runtime.esm.js:4495:25)
    at bn.evaluate (vue.runtime.esm.js:4597:21)
    at o.userAsAttendee (vue.runtime.esm.js:4851:17)
    at o.isViewedByAttendee (EditorMixin.js:222:16)
    at bn.get (vue.runtime.esm.js:4495:25)
    at bn.evaluate (vue.runtime.esm.js:4597:21)
    at o.isViewedByAttendee (vue.runtime.esm.js:4851:17)
    at o.<anonymous> (EditSimple.vue?vue&type=template&id=7e53e5ba&:1:4571)
```
```


### Additional info

contents of the `$store.getters.getCurrentUserPrincipal` getter result on error
```
{
    "id": "█████████████████",
    "calendarUserType": "INDIVIDUAL",
    "displayname": "█████",
    "principalScheme": "principal:principals/users/█████",
    "userId": "█████",
    "url": "/remote.php/dav/principals/users/█████/",
    "dav": {
        "_eventListeners": {},
        "_parent": null,
        "_request": {
            "baseUrl": "https://cloud.███████/remote.php/dav/",
            "parser": {
                "_parser": {}
            }
        },
        "_url": "/remote.php/dav/principals/users/█████/",
        "_props": {
            "{DAV:}displayname": "█████",
            "{urn:ietf:params:xml:ns:caldav}calendar-user-type": "INDIVIDUAL",
            "{urn:ietf:params:xml:ns:caldav}calendar-user-address-set": [
                "/remote.php/dav/principals/users/█████/"
            ],
            "{DAV:}principal-URL": "/remote.php/dav/principals/users/█████/",
            "{DAV:}alternate-URI-set": [],
            "{http://nextcloud.com/ns}language": "en",
            "{urn:ietf:params:xml:ns:caldav}calendar-home-set": [
                "/remote.php/dav/calendars/█████/"
            ],
            "{urn:ietf:params:xml:ns:caldav}schedule-inbox-URL": "/remote.php/dav/calendars/█████/inbox/",
            "{urn:ietf:params:xml:ns:caldav}schedule-outbox-URL": "/remote.php/dav/calendars/█████/outbox/",
            "{DAV:}principal-collection-set": [
                "/remote.php/dav/principals/users/",
                "/remote.php/dav/principals/groups/",
                "/remote.php/dav/principals/calendar-resources/",
                "/remote.php/dav/principals/calendar-rooms/"
            ]
        },
        "_isPartial": false,
        "_isDirty": false
    },
    "isCircle": false,
    "isUser": true,
    "isGroup": false,
    "isCalendarResource": false,
    "isCalendarRoom": false,
    "principalId": "█████"
}
```

**Comment by krumelmonster** [comment]
The same symptoms and exception appear when accessing this calendar through a public share link and in this case, setting a user mail adress won't help (because there is no user in case of a public access link).
![image](https://user-images.githubusercontent.com/13542760/167409926-823e27ce-d4b8-46da-b996-7b79629b96ae.png)

**Comment by krumelmonster** [comment]
I updated the report accordingly. I also ran both the original ics calendar which I synced to nextcloud and an ics export of the nextcloud calendar through this validator https://icalendar.org/validator.html but it reported no issues.

**Comment by pierreozoux** [comment]
Can also reproduce, Nc 24.
