### ISSUE TITLE
Appointment modal doesn't open. It shows loader only. 

### ISSUE THREAD

**Issue by mudassir1996** [nextcloud/calendar#5003]
### Steps to reproduce

1. Create a new Appointments calendar.
2. Book a slot on this calendar by using the public link.
3. Go to calendar and click on booked appointment.

### Expected behavior

Appointment modal should be open.

### Actual behaviour

Appointment modal shows loader only

### Calendar app version

3.5.5

### Browser

Microsoft Edge Version 110.0.1587.50 (Official build) (64-bit)

### Client operating system

Windows 11 Pro V 22H2 x64

### Server operating system

Ubuntu 20.04.5 LTS

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 7.4

### Nextcloud version

22.2.10

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
- accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - appointments: 1.12.8
  - approval: 1.0.10
  - auto_groups: 1.4.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - data_request: 1.9.0
  - dav: 1.20.0
  - deck: 1.5.8
  - event_update_notification: 1.5.0
  - extract: 1.3.5
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_3d: 0.5.0
  - files_accesscontrol: 1.12.2
  - files_antivirus: 3.3.1
  - files_automatedtagging: 1.12.0
  - files_downloadactivity: 1.15.0
  - files_downloadlimit: 1.0.1
  - files_fulltextsearch: 22.0.3
  - files_fulltextsearch_tesseract: 22.0.0
  - files_lock: 20.1.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - files_zip: 1.1.2
  - flow_notifications: 1.2.1
  - fulltextsearch: 22.0.1
  - fulltextsearch_elasticsearch: 22.0.2
  - group_default_quota: 0.1.4
  - groupfolders: 10.0.4
  - integration_whiteboard: 0.0.14
  - jitsi: 0.15.0
  - login_notes: 1.0.4
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.14.1
  - metadata: 0.17.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.4.6
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.14.0
  - ransomware_protection: 1.13.0
  - recognize: 2.1.2
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - side_menu: 2.5.1
  - spreed: 12.2.7
  - suspicious_login: 4.2.1
  - systemtags: 1.12.0
  - terms_of_service: 1.8.5
  - text: 3.3.1
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_email: 2.7.1
  - twofactor_totp: 6.4.1
  - user_ldap: 1.12.2
  - viewer: 1.6.0
  - workflow_ocr: 1.22.5
  - workflow_pdf_converter: 1.7.0
  - workflowengine: 2.4.0
Disabled:
  - encryption: 2.10.0
  - files_external
  - ocr: 6.0.58
  - richdocuments
  - richdocumentscode
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "SG",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "integrity.check.disabled": true,
        "trashbin_retention_obligation": "365, auto",
        "knowledgebaseenabled": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.10.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl"
    }
}
```

### Browser log

```Text
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at sz (attendee.js:30:10)
    at o.userAsAttendee (EditorMixin.js:234:22)
    at t.get (vue.runtime.esm.js:3517:33)
    at t.evaluate (vue.runtime.esm.js:3618:27)
    at o.userAsAttendee (vue.runtime.esm.js:5339:25)
    at o.isViewedByAttendee (EditorMixin.js:222:16)
    at t.get (vue.runtime.esm.js:3517:33)
    at t.evaluate (vue.runtime.esm.js:3618:27)
    at o.isViewedByAttendee (vue.runtime.esm.js:5339:25)
    at o.<anonymous> (EditSimple.vue:1:5009)
```

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/blob/7de408b7df01ffa2715356cdee377cb5cbcdb1b5/src/utils/attendee.js#L30

**Comment by masonbrothers** [comment]
Might be fixed in https://github.com/nextcloud/calendar/pull/5170
