### ISSUE TITLE
Maximum call stack exceeded when clicking the `Show more events` heading link

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/calendar#5654]
### Steps to reproduce

1. Have multiple day events
2. See the `xxx more events` button
3. Click on it
![2024-01-02_14-30](https://github.com/nextcloud/calendar/assets/14975046/680d8886-2bd6-45e9-9b1b-75592c75b92f)

### Expected behavior

- Popup opens instantly

### Actual behaviour

- Nothing happens first
- After a while (2-3 minutes) the popup opens with a console error
- The UI gets frozen

### Calendar app version

5.6.1

### Browser

Brave version 1.60.125 Chromium: 119.0.6045.199 (Build officiel) (64 bits)

### Client operating system

Arch btw

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

28.0.1

### Updated from an older installed version or fresh install

None

### Log file

```Text
sentry.js?v=a0438487-1764:2 Uncaught RangeError: Maximum call stack size exceeded
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
    at Vh.handleInvalidInsertion (internal.js:414:22)
    at Vh.insertEntry (internal-common.js:5765:21)
    at Vh.splitEntry (internal-common.js:5792:29)
    at Vh.handleInvalidInsertion (internal-common.js:5774:25)
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
splitEntry	@	internal-common.js:5792
handleInvalidInsertion	@	internal-common.js:5774
handleInvalidInsertion	@	internal.js:414
insertEntry	@	internal-common.js:5765
setTimeout (async)		
(anonymous)	@	sentry.js?v=a0438487-1764:2
l	@	index.js:23
r	@	sentry.js?v=a0438487-1764:2
setTimeout (async)		
(anonymous)	@	sentry.js?v=a0438487-1764:2
l	@	index.js:23
r	@	sentry.js?v=a0438487-1764:2
setTimeout (async)		
(anonymous)	@	sentry.js?v=a0438487-1764:2
c
```

**Comment by skjnldsv** [comment]
Now I also get this on creating any event.
Browsing weeks is inpossible

cc @nextcloud/groupware

**Comment by ChristophWurst** [comment]
Sadly, this is known.

Please don't ping the full team. @miaulalala is monitoring new tickets in this repo :pray:

**Comment by st3iny** [comment]
Certainly looks a bit like it:
> Brave version 1.60.125 Chromium

**Comment by ChristophWurst** [comment]
To simulate a lot of data/events

## 1h events

```bash
#!/bin/bash

CREATED_AT=$(TZ=UTC date +"%Y%m%dT%H%M%SZ")

# Header
cat <<ICS
BEGIN:VCALENDAR
PRODID:-//IDN nextcloud.com//Calendar app 4.7.0-beta.4//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Vienna
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
ICS

# Events
for i in {1..1000}
do
  EVENT_UID=$(LC_ALL=C tr -dc a-f0-9 </dev/urandom | head -c 32)
  DTSTART=$(TZ=Europe/Vienna date -d "2024-03-01 - 1 hour + $i hours" +"%Y%m%dT%H%M%S")
  DTEND=$(TZ=Europe/Vienna date -d "2024-03-01 + $i hours" +"%Y%m%dT%H%M%S")

  cat <<ICS
BEGIN:VEVENT
CREATED:${CREATED_AT}
DTSTAMP:${CREATED_AT}
LAST-MODIFIED:${CREATED_AT}
SEQUENCE:0
UID:${EVENT_UID}
DTSTART;TZID=Europe/Vienna:${DTSTART}
DTEND;TZID=Europe/Vienna:${DTEND}
STATUS:CONFIRMED
SUMMARY:Test ${i}
END:VEVENT
ICS
done

# Footer
cat <<ICS
END:VCALENDAR
ICS
```

## Full day events

```bash
#!/bin/bash

CREATED_AT=$(TZ=UTC date +"%Y%m%dT%H%M%SZ")

# Header
cat <<ICS
BEGIN:VCALENDAR
PRODID:-//IDN nextcloud.com//Calendar app 4.7.0-beta.4//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Vienna
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
ICS

# Events
for i in {1..1000}
do
  EVENT_UID=$(LC_ALL=C tr -dc a-f0-9 </dev/urandom | head -c 32)
  DTSTART=$(TZ=Europe/Vienna date -d "2024-03-01 - 1 hour + $i hours" +"%Y%m%d")
  DTEND=$(TZ=Europe/Vienna date -d "2024-03-01 + $i hours" +"%Y%m%d")

  cat <<ICS
BEGIN:VEVENT
CREATED:${CREATED_AT}
DTSTAMP:${CREATED_AT}
LAST-MODIFIED:${CREATED_AT}
SEQUENCE:0
UID:${EVENT_UID}
DTSTART;TZID=Europe/Vienna:${DTSTART}
DTEND;TZID=Europe/Vienna:${DTEND}
STATUS:CONFIRMED
SUMMARY:Test ${i}
END:VEVENT
ICS
done

# Footer
cat <<ICS
END:VCALENDAR
ICS
```

however, it doesn't allow me to reproduce the *Maximum call stack exceeded* bug on Firefox or Chromium.

**Comment by ChristophWurst** [comment]
I can also not reproduce this with a build before https://github.com/nextcloud/calendar/pull/5783.

**Comment by SebastianKrupinski** [comment]
Closing this as no longer reproducible
