### ISSUE TITLE
Add attachment (Nextcloud internal) popup does not show files and folders

### ISSUE THREAD

**Issue by gibelium** [nextcloud/calendar#6004]
### Steps to reproduce

1. Create an calendar event
2. Click "+" sign to add an attachment
3. Select "Add from Files"
4. The file selector Popup does not show files

### Expected behavior

The popup showing the file selector for files that already reside in Nextcloud should display the files and folders to be able to select the file you would like to attach.

### Actual behaviour

The file selector does not display any files or folders

### Calendar app version

4.7.3

### Browser

Firefox 125.0.3

### Client operating system

Mac OS 13.6.6

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

28.0.5

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
Can confirm it doesn't work on Chrome for me:

```
AttachmentsList.vue:67 [Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().

found in

---> <DialogBase>
       <FilePicker>
         <Root>
warn @ vue.runtime.esm.js:4625
(anonymous) @ vue.runtime.esm.js:3301
useMounted @ index.mjs:502
useSupported @ index.mjs:510
useResizeObserver @ index.mjs:2522
useElementSize @ index.mjs:2680
setup @ DialogBase-aNq6aLpb.mjs:80
invokeWithErrorHandling @ vue.runtime.esm.js:3033
initSetup @ vue.runtime.esm.js:2457
initState @ vue.runtime.esm.js:5385
Vue._init @ vue.runtime.esm.js:5714
VueComponent @ vue.runtime.esm.js:5849
createComponentInstanceForVnode @ vue.runtime.esm.js:4564
init @ vue.runtime.esm.js:4426
createComponent @ vue.runtime.esm.js:6591
createElm @ vue.runtime.esm.js:6545
patch @ vue.runtime.esm.js:7095
Vue._update @ vue.runtime.esm.js:3781
updateComponent @ vue.runtime.esm.js:3891
Watcher.get @ vue.runtime.esm.js:3462
Watcher @ vue.runtime.esm.js:3452
mountComponent @ vue.runtime.esm.js:3908
Vue.$mount @ vue.runtime.esm.js:8797
init @ vue.runtime.esm.js:4427
createComponent @ vue.runtime.esm.js:6591
createElm @ vue.runtime.esm.js:6545
patch @ vue.runtime.esm.js:7133
Vue._update @ vue.runtime.esm.js:3781
updateComponent @ vue.runtime.esm.js:3891
Watcher.get @ vue.runtime.esm.js:3462
Watcher @ vue.runtime.esm.js:3452
mountComponent @ vue.runtime.esm.js:3908
Vue.$mount @ vue.runtime.esm.js:8797
Vue._init @ vue.runtime.esm.js:5724
Vue @ vue.runtime.esm.js:5785
M @ legacy.mjs:33
z @ legacy.mjs:100
(anonymous) @ index-X06k2874.mjs:17
pick @ index-X06k2874.mjs:10
await in pick (async)
openFilesModal @ AttachmentsList.vue:67
click @ AttachmentsList.vue:47
invokeWithErrorHandling @ vue.runtime.esm.js:3033
invoker @ vue.runtime.esm.js:1832
invokeWithErrorHandling @ vue.runtime.esm.js:3033
Vue.$emit @ vue.runtime.esm.js:3732
onClick @ actionText-bMy_49i8.mjs:118
handleClick @ NcActionButton.mjs:113
invokeWithErrorHandling @ vue.runtime.esm.js:3033
invoker @ vue.runtime.esm.js:1832
original_1._wrapper @ vue.runtime.esm.js:7500
Show 48 more frames
Show less
AttachmentsList.vue:67 [Vue warn]: Error in mounted hook (Promise/async): "TypeError: Cannot read properties of undefined (reading 'authType')"

found in

---> <FilePicker>
       <Root>
warn @ vue.runtime.esm.js:4625
logError @ vue.runtime.esm.js:3061
globalHandleError @ vue.runtime.esm.js:3057
handleError @ vue.runtime.esm.js:3024
(anonymous) @ vue.runtime.esm.js:3035
Promise.catch (async)
invokeWithErrorHandling @ vue.runtime.esm.js:3035
callHook$1 @ vue.runtime.esm.js:4048
insert @ vue.runtime.esm.js:4443
invokeInsertHook @ vue.runtime.esm.js:6966
patch @ vue.runtime.esm.js:7180
Vue._update @ vue.runtime.esm.js:3781
updateComponent @ vue.runtime.esm.js:3891
Watcher.get @ vue.runtime.esm.js:3462
Watcher @ vue.runtime.esm.js:3452
mountComponent @ vue.runtime.esm.js:3908
Vue.$mount @ vue.runtime.esm.js:8797
Vue._init @ vue.runtime.esm.js:5724
Vue @ vue.runtime.esm.js:5785
M @ legacy.mjs:33
z @ legacy.mjs:100
(anonymous) @ index-X06k2874.mjs:17
pick @ index-X06k2874.mjs:10
await in pick (async)
openFilesModal @ AttachmentsList.vue:67
click @ AttachmentsList.vue:47
invokeWithErrorHandling @ vue.runtime.esm.js:3033
invoker @ vue.runtime.esm.js:1832
invokeWithErrorHandling @ vue.runtime.esm.js:3033
Vue.$emit @ vue.runtime.esm.js:3732
onClick @ actionText-bMy_49i8.mjs:118
handleClick @ NcActionButton.mjs:113
invokeWithErrorHandling @ vue.runtime.esm.js:3033
invoker @ vue.runtime.esm.js:1832
original_1._wrapper @ vue.runtime.esm.js:7500
Show 31 more frames
Show less
AttachmentsList.vue:67 TypeError: Cannot read properties of undefined (reading 'authType')
    at request (request.js:71:1)
    at index.mjs:405:1
    at index.js:2:1
    at _.execute (index.js:2:1)
    at _.patchInline (index.js:2:1)
    at Q (index.js:2:1)
    at index.js:2:1
    at index.js:2:1
    at index.js:2:1
    at n (index.js:2:1)
```

**Comment by miaulalala** [comment]
Also happens in Mail on Chrome for me.
