### ISSUE TITLE
Unable to open primary script after update to 1.5.4

### ISSUE THREAD

**Issue by simonspa** [nextcloud/calendar#603]
### Steps to reproduce
1. Run Nextcloud 12.0.2
2. Update calendar to 1.5.4
3. Try to open the calendar 1.5.4 app

### Expected behaviour
The calendar app opens just as it did before updating (up to version 1.5.3)

### Actual behaviour
The server reports:

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request.
> 
> Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
> 
> More details can be found in the server log.
> 
> Technical details
> 
>     Remote Address: 128.141.234.226
>     Request ID: UJLQUmYQfFe7VDiwVDFY
> 

And the logs reveal:

```
2017/09/15 14:42:52 [error] 10734#0: *1878 FastCGI sent in stderr: "Unable to open primary script: /var/www/nextcloud/index.php/apps/calendar/ocs/v2.php (No such file or directory)" while reading response header from upstream, client: <IP>, server: <HOST>, request: "GET /apps/calendar/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "<HOST>"
```

### Server configuration

**Operating system**:  Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux on Raspberry Pi 2B

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 

**Server version:** 12.0.2

**Calendar version:** 1.5.4

**Updated from an older installed version or fresh install:** Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
sudo -u www-data php occ app:list
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - audioplayer: 2.1.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.4
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_markdown: 2.0.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - gpxedit: 0.0.7
  - gpxmotion: 0.0.5
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.2
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - deck
  - encryption
  - survey_client
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "oc0e7rzi20xo",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.2.130",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/data\/ocdata",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "timeout": 0
        },
        "log_rotate_size": "100MiB",
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "notifications",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "updater.release.channel": "stable"
    }
}

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 55.02

**Operating system:** Ubuntu 17.04

**CalDAV-clients:** (web)

#### Web server error log

```
2017/09/15 14:42:52 [error] 10734#0: *1878 FastCGI sent in stderr: "Unable to open primary script: /var/www/nextcloud/index.php/apps/calendar/ocs/v2.php (No such file or directory)" while reading response header from upstream, client: <IP>, server: <HOST>, request: "GET /apps/calendar/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "<HOST>"
```

#### Log file (data/nextcloud.log)
```
{"reqId":"pO8bry8RyfeZ35Sgvwkz","level":3,"time":"2017-09-15T12:56:21+00:00","remoteAddr":"128.141.234.226","user":"smn","app":"index","method":"GET","url":"\/apps\/calendar\/","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"template file not found: template:main\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(174): OC\\\\Template\\\\TemplateFileLocator->find('main')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(85): OC_Template->findTemplate('', 'calendar', 'main')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(151): OC_Template->__construct('calendar', 'main', 'user')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Calendar\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/calendar\\\/')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/TemplateFileLocator.php\",\"Line\":56}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.2.0"}
```

**Comment by tcitworld** [comment]
This looks like a webserver misconfiguration, if I'm reading this right : the notification endpoint is called from `/apps/calendar` instead of `/`. Probably a missing `/` somewhere.
What is the address in your browser when you're accessing the calendar ?

**Comment by simonspa** [comment]
it's `https://cloud.mydomain.tld/apps/calendar/`. I wonder how this could happen as I didn't change the server configuration but simply update the app.

**Comment by tcitworld** [comment]
Can you confirm the calendar is the only app with this issue ?

**Comment by simonspa** [comment]
I can confirm this. All other installed apps work fine: Gallery, Audio Player, Contacts, Notes, Tasks...

**Comment by simonspa** [comment]
After updating to the recent 1.5.5 everything works again as expected. Maybe something went wrong during the previous install?

Thanks anyway for your patience, closing this issue.
