### ISSUE TITLE
Calendar suddenly won't load at all!

### ISSUE THREAD

**Issue by atomspring** [nextcloud/calendar#647]
### Steps to reproduce
1. Go to calendar app

### Expected behaviour
Calendar app should load as it did on version 11. Contacts are also not working after upgrading to 2.0.1, though the server doesn't jump to the "internal error" screen, just sits and tries to load.

### Actual behaviour
I get a message about an internal server error with these details in the log:
![screenshot-2017-10-31 admin - atomspring](https://user-images.githubusercontent.com/9324477/32230149-e20354fa-be28-11e7-94e5-e948c5732cc3.png)

### Server configuration

**Operating system**: Ubuntu Server 16.04 LTS x64

**Web server:** Nginx 1.11.2

**Database:** Mysql 10

**PHP version:** 7.0.22

**Server version:** 12.0.3-12.0.3.3

**Calendar version:** 1.5.6

**Updated from an older installed version or fresh install:** Upgrade

**Signing status (ownCloud/Nextcloud 9.0 and above):** No errors found

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - survey_client
  - user_external
  - user_ldap

```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "ocxvl1kp2ir4",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "files.homenet"
        ],
        "datadirectory": "\/var\/www\/data",
        "overwrite.cli.url": "https:\/\/files.homenet",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "farquad",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "dbindex": 0
        },
        "mail_from_address": "system",
        "mail_smtpmode": "php",
        "mail_domain": "homeNet",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 57beta10

**Operating system:** Ubuntu 16.04

**CalDAV-clients:** Davdroid latest

#### Web server error log
Nothing of note

#### Log file (data/nextcloud.log)
    "reqId":"Xm6HxKXoPF2KuLGf1qxK",
    "level":3,
    "time":"2017-10-31T14:41:52+00:00",
    "remoteAddr":"192.168.5.205",
    "user":"operator",
    "app":"index",
    "method":"GET",
    "url":"\/apps\/calendar\/",
    "message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"template file not found: template:main\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(174): OC\\\\Template\\\\TemplateFileLocator->find('main')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(85): OC_Template->findTemplate('', 'calendar', 'main')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(151): OC_Template->__construct('calendar', 'main', 'user')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Calendar\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/calendar\\\/')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/TemplateFileLocator.php\",\"Line\":56}",
    "userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0",
    "version":"12.0.3.3"
#### Browser log
```JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
ReferenceError: oc_appconfig is not defined
[Learn More]
merged-share-backend.js:24:4
TypeError: link is undefined
[Learn More]
merged-template-prepend.js:1349:1
data.ocs.data is undefined or not an array
merged.js:446:6
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://files.homeNET/core/vendor/core.js?v=cc4b2538e3de064c442fabba4b842af4-22
Source Map URL: purify.min.js.map
[Learn More]
data.ocs.data is undefined or not an array```

**Comment by atomspring** [comment]
Strangely the calendar app was fine on 12.0.3 as recently as a few days ago. Nothing's changed server-side, this suddenly won't work as of this morning.

**Comment by tcitworld** [comment]
Looks like a file is missing. Could you try uninstalling and reinstalling the app (it won't delete any data) ?

**Comment by atomspring** [comment]
@tcitworld You were correct. How did this file vanish? I have no entries in my auth.log or any other logs indicating illicit access...

**Comment by atomspring** [comment]
Incidentally, doing the same process with contacts restored functionality as well. The upgrade from 12.0 to 12.0.3 is the only time I've ever used the upgrade wizard to download and update my install. Perhaps there's a subtle issue with the upgrade wizard?
