### ISSUE TITLE
SameOrganizerForAllComponentsException

### ISSUE THREAD

**Issue by esprit-libre** [nextcloud/calendar#683]
### Steps to reproduce
Not sure because it comes from a customer
1. Create a recurrent event in a shared calendar, with no end date. User that creates it is not the owner of the calendar
2. Edit the event with another user, also not the owner of the calendar
3. Edit again with any other user

### Expected behaviour
Modification should works without errors.

### Actual behaviour
SameOrganizerForAllComponentsException is thrown

### Server configuration
**Operating system**:
Debian 9
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.0.19
**Server version:** (see your admin page)
12.0.2
**Calendar version:** (see the apps page)
1.5.7

**Are you using encryption:** yes/no
No

### Client configuration
**Browser:**
Any (Thunderbird+Lightning, Firefox)
**Operating system:**
Ubuntu and Windows tested

#### Log file (data/nextcloud.log)
```
{"reqId":"FjOEMcc23SglbJ5bGKvC","level":4,"time":"2017-12-14T16:49:14+01:00","remoteAddr":"109.190.199.43","user":"espritlibre","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/calendars\/espritlibre\/personnel_shared_by_AlterBative\/l1lqont3fu4bosvu7meohnf47o%40google.com.ics","message":"Exception: {\"Exception\":\"Sabre\\\\VObject\\\\ITip\\\\SameOrganizerForAllComponentsException\",\"Message\":\"Every instance of the event must have the same organizer.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/ITip\\\/Broker.php(180): Sabre\\\\VObject\\\\ITip\\\\Broker->parseEventInfo(Object(Sabre\\\\VObject\\\\Component\\\\VCalendar))\\n#1 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Schedule\\\/Plugin.php(427): Sabre\\\\VObject\\\\ITip\\\\Broker->parseEvent(NULL, Array, Object(Sabre\\\\VObject\\\\Component\\\\VCalendar))\\n#2 [internal function]: Sabre\\\\CalDAV\\\\Schedule\\\\Plugin->beforeUnbind('calendars\\\/espri...')\\n#3 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(286): Sabre\\\\Event\\\\EventEmitter->emit('beforeUnbind', Array)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#8 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/alterbative\\\/www\\\/apps\\\/dav\\\/lib\\\/Server.php(253): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/home\\\/alterbative\\\/www\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/home\\\/alterbative\\\/www\\\/remote.php(162): require_once('\\\/home\\\/alterbative....')\\n#12 {main}\",\"File\":\"\\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/ITip\\\/Broker.php\",\"Line\":871}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Thunderbird\/52.5.0 Lightning\/5.4","version":"12.0.2.0"}
```

**Comment by georgehrke** [comment]
Was the event edited in the webcalendar or in some other calendar client?

**Comment by esprit-libre** [comment]
I guess in Thunderbird because all users are working with it.

**Comment by georgehrke** [comment]
In that case:

Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by esprit-libre** [comment]
When trying to edit in webcalendar, no error appears but no change can be done. Error can only be shown in logs.

So ok, I report to server part.
